### ISSUE TITLE
Will datasets be available ?

### ISSUE THREAD

**Issue by CGeorges** [textualinsightsDev/SentimentEngine#1]
Hi, thank you for releasing your sentiment engine, it's a real jewel. Will the datasets ever be released also ? 

Thanks,
Georges

**Comment by textualinsightsDev** [comment]
Its scraped data. Not even ours. So we can't release it. And the data
preparation is proprietary. It makes sure the model is domain independent.
You would see only tokenization in the data preparation of test data (from
the code that is released). But the data preparation is different for
training data. So the corresponding code to build model is also not
released.

Regards,
Textual Insights
